channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=1.1.4
- nodejs=10.13
- nbconvert=5.6
- widgetsnbextension=3.5.1
- jupyter_contrib_nbextensions
# Python Kernel
- ipykernel=5.1.2
- ipywidgets=7.5.1
- ipyleaflet=0.11.1
- altair=3.1
- bqplot=0.11.6
- dask=2.1
- matplotlib=3.1
- pandas=0.25.1
- python=3.7
- scikit-image=0.15
- scikit-learn=0.21
- seaborn=0.9
- tensorflow=1.13
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
